---
abstract: 'A Turing Complete Language for Mathematics'
author:
  - 'Ryan Voots <simcop@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Language-Farnsworth
no_index:
  directory:
    - inc
    - t
recommends:
  Finance::Currency::Convert::XE: 0
  REST::Google::Translate: 0
requires:
  DateTime: 0
  DateTimeX::Easy: 0
  List::MoreUtils: 0
  Math::Pari: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.6.0
